config/routes.rb
Rails.application.routes.draw do
resources :gossips
resources :users
resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/concerns/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true, length: { in: 3..14}
	validates :content, presence: true
	belongs_to :user
	has_many :join_table_gossips_tags
	has_many :tags, through: :join_table_gossips_tags
end

app/models/concerns/join_table_gossips_tag.rb
class JoinTableGossipsTag < ApplicationRecord
	belongs_to :tag 
	belongs_to :gossip

end

app/models/concerns/join_table_message_recipient.rb
class JoinTableMessageRecipient < ApplicationRecord
	belongs_to :recipient, class_name: "User"
  	belongs_to :private_message
end

app/models/concerns/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
  has_many :join_table_message_recipients
  has_many :recipients, class_name: "User", through: :join_table_message_recipients
end

app/models/concerns/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_gossips_tags
	has_many :gossips, through: :join_table_gossips_tags
end

app/models/concerns/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city, optional: true 
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  	has_many :received_messages, foreign_key: 'recipient_id', class_name: "JoinTableMessageRecipient"
  	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:show, :new, :create]
  before_action :only_user, only: [:edit, :update, :destroy]

	def index
		@gossips = Gossip.all
	end

	def show
    @gossip = Gossip.find(params[:id])
  end

  def new # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  	@gossip = Gossip.new
  end

  def create
  	@gossip = Gossip.new(title: params[:title],content: params[:content],user: current_user)
    if @gossip.save
    	puts 'la sauvegarde a fonctionné'
    	flash[:success] = "Votre gossip à bien été enregistré !"
    	redirect_to gossips_path
  	else
    	puts 'la sauvegarde n a pas fonctionné'
  		render 'new'
    end	
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    post_params = params.require(:gossip).permit(:title, :content)
    if @gossip.update(post_params)
      puts 'modif prise en compte'
      redirect_to gossips_path
    else
      puts 'modif non prise en compte'
      render 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

    def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
      end
    end

  
    def only_user
      @gossip = Gossip.find(params[:id])
    unless current_user == @gossip.user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  user = User.find_by(email: params[:email])
  puts user
  	if user && user.authenticate(params[:password])
  		puts 'le login a marché'
    	session[:user_id] = user.id
    	redirect_to gossips_path
  	else
  		puts 'le login n a pas marché'
    	flash.now[:danger] = 'Invalid email/password combination'
    	render 'new'
  	end
	end

  def destroy
  	session.delete(:user_id)
  	puts 'le loug-out a marché'
  	redirect_to gossips_path
	end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def team
	end
	
	def contact
	end

	def welcome
	@first_name = params["first_name"]
	puts "ton first_name est params #{["first_name"]}"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
 	end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(first_name: params[:first_name],last_name: params[:last_name],email: params[:email], password: params[:password])
  	if @user.save
  		puts 'l inscription a fonctionné'
  		session[:user_id] = user.id
  		redirect_to gossips_path
  	else
  		puts 'l inscription n a pas fonctionné'
  		render 'new'
  	end	
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   	def current_user
    User.find_by(id: session[:user_id])
  	end

   	def log_in(user)
    session[:user_id] = user.id
  	end

end

app/views/gossips/edit.html.erb
<h1>Editer le gossip</h1>

<%= form_for @gossip do |f|%>

<div class="form-group">
  <label>Titre du gossip</label>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <label>Contenu du gossip</label>
  <%= f.text_area :content, class: 'form-control' %>
</div>

<div class="form_group">
  <button type="submit" class = "btn btn-primary">Modifier le gossip</button>
</div>

<% end %>

app/views/gossips/index.html.erb
<h1>Gossips</h1>

<% @gossips.each do |gossip| %>
<h2><%= gossip.title %></h2>
<p><%= gossip.content %></p>
<a href="<%= gossip_path(gossip.id)%>" class="btn btn-primary">Lire la suite</a>
<a href="<%= edit_gossip_path(gossip.id)%>" class="btn btn-default">Editer</a>
<a href="<%= gossip_path(gossip.id)%>" class="btn btn-danger" data-confirm="êtes-vous sûr?" data-method="DELETE">Supprimer</a>
<% end %>

app/views/gossips/new.html.erb
<div class="container">
	<h1>Crée un potin !</h1>
	<p>Balance ton potin via le formulaire ci-dessous</p>

 <%= form_tag url_for(action: 'create'), method: "post" do %>

 <div class="form-group">
   <%= label_tag 'Title' %>
   <%= text_field_tag 'title', 'Titre du Gossip', class: 'form-control' %>
   <br /> <br />
 </div>

 <div class="form-group">
   <%= label_tag 'Body' %>
   <%= text_area_tag 'content', 'content', class: 'form-control' %>
   <br /> <br />
 </div>

 <%= submit_tag "Create Post" %>

<% end %>

</div>

app/views/gossips/show.html.erb
<h1><%= @gossip.title %></h1>

<p><%= @gossip.content %></p>

<p>
<a href="<%= gossips_path %>" class= "btn btn-primary">Revenir aux gossips</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>TheGossipProject</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" <%= link_to "The Gossip Project", gossips_path %>></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <%= link_to "Liste des Gossips", gossips_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Créer un gossip", new_gossip_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "S'inscrire", new_user_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Login", new_session_path, class: "nav-link" %>
          </li>

        </ul>
      </div>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
          <%= link_to "Se déconnecter", session_path(session.id), method: :delete %>
          </li>

        </ul>
      </div>

    </nav>

    <div class="jumbotron">
    </div>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

app/views/users/new.html.erb
<div class="container">
	<h1>Inscription</h1>
	<p>Pour t'inscrire, voici le formulaire à remplir</p>

   <%= form_tag url_for(action: 'create'), method: "post" do %>

	 <div class="form-group">
     <%= label_tag 'first_name' %>
     <%= text_field_tag 'first_name', 'first_name', class: 'form-control' %>
     <br /> <br />
   </div>

	 <div class="form-group">
     <%= label_tag 'last_name' %>
     <%= text_field_tag 'last_name', 'last_name', class: 'form-control' %>
     <br /> <br />
   </div>

   <div class="form-group">
     <%= label_tag 'email' %>
     <%= text_field_tag 'email', 'email', class: 'form-control' %>
     <br /> <br />
   </div>

   <div class="form-group">
     <%= label_tag 'password' %>
     <%= text_field_tag 'password', 'password', class: 'form-control' %>
     <br /> <br />
   </div>

   <%= submit_tag "Inscription" %>

  <% end %>

  </div>

app/views/users/show.html.erb
<p><%= @user.first_name %></p>
<p><%= @user.last_name %></p>
<p><%= @user.description %></p>
<p><%= @user.email %></p>
<p><%= @user.age %></p>
<p><%= @user.city_id %></p>